spring:
  application:
    name: loja-online-pedido-be

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

  datasource:
    url: jdbc:postgresql://db:5432/loja
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: INFO
    com.actdigital.lojaonlinepagamentobe: DEBUG
    org.springframework.amqp: INFO
